version: '3'

services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    container_name: nginx
    ports:
      - "${DOCKER_WEBSERVER_HOST}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
      - db
    networks:
      - unifiedtransform

  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - db_database:/var/lib/mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT_DOCKER}:${DB_PORT}
    networks:
      - unifiedtransform

  php:
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - unifiedtransform

networks:
  unifiedtransform:
    driver: bridge

volumes:
  db_database:
    driver: local
